name: updateforks
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: >
          gh repo sync https://github.com/luncher-org/PushProx ;
          gh repo sync https://github.com/luncher-org/Rancher-Plugin-gMSA ;
          gh repo sync https://github.com/luncher-org/actions ;
          gh repo sync https://github.com/luncher-org/aks-operator ;
          gh repo sync https://github.com/luncher-org/api-ui ;
          gh repo sync https://github.com/luncher-org/apiserver ;
          gh repo sync https://github.com/luncher-org/autoscaler ;
          gh repo sync https://github.com/luncher-org/aws-janitor ;
          gh repo sync https://github.com/luncher-org/azure-janitor ;
          gh repo sync https://github.com/luncher-org/backup-restore-operator ;
          gh repo sync https://github.com/luncher-org/barn ;
          gh repo sync https://github.com/luncher-org/build-tekton ;
          gh repo sync https://github.com/luncher-org/busybox ;
          gh repo sync https://github.com/luncher-org/calico ;
          gh repo sync https://github.com/luncher-org/calico-cni ;
          gh repo sync https://github.com/luncher-org/capi-ui-extension ;
          gh repo sync https://github.com/luncher-org/cert-manager ;
          gh repo sync https://github.com/luncher-org/certgen ;
          gh repo sync https://github.com/luncher-org/channelserver ;
          gh repo sync https://github.com/luncher-org/charts ;
          gh repo sync https://github.com/luncher-org/charts-build-scripts ;
          gh repo sync https://github.com/luncher-org/charts-small-fork ;
          gh repo sync https://github.com/luncher-org/cilium ;
          gh repo sync https://github.com/luncher-org/cis-operator ;
          gh repo sync https://github.com/luncher-org/cli ;
          gh repo sync https://github.com/luncher-org/cloud-provider-harvester ;
          gh repo sync https://github.com/luncher-org/cloud-provider-vsphere ;
          gh repo sync https://github.com/luncher-org/cluster-api-provider-rancher ;
          gh repo sync https://github.com/luncher-org/cluster-api-provider-rke2 ;
          gh repo sync https://github.com/luncher-org/cluster-proportional-autoscaler ;
          gh repo sync https://github.com/luncher-org/cluster-template-examples ;
          gh repo sync https://github.com/luncher-org/community-extensions ;
          gh repo sync https://github.com/luncher-org/confd ;
          gh repo sync https://github.com/luncher-org/coredns ;
          gh repo sync https://github.com/luncher-org/crd-swagger ;
          gh repo sync https://github.com/luncher-org/csi-attacher ;
          gh repo sync https://github.com/luncher-org/csi-node-driver-registrar ;
          gh repo sync https://github.com/luncher-org/csi-provisioner ;
          gh repo sync https://github.com/luncher-org/csi-resizer ;
          gh repo sync https://github.com/luncher-org/csp-adapter ;
          gh repo sync https://github.com/luncher-org/dapper ;
          gh repo sync https://github.com/luncher-org/dartboard ;
          gh repo sync https://github.com/luncher-org/dashboard ;
          gh repo sync https://github.com/luncher-org/demo-renovate ;
          gh repo sync https://github.com/luncher-org/digitalocean-janitor ;
          gh repo sync https://github.com/luncher-org/distros-test-framework ;
          gh repo sync https://github.com/luncher-org/dns ;
          gh repo sync https://github.com/luncher-org/docker ;
          gh repo sync https://github.com/luncher-org/docs ;
          gh repo sync https://github.com/luncher-org/dynamiclistener ;
          gh repo sync https://github.com/luncher-org/ecm-distro-tools ;
          gh repo sync https://github.com/luncher-org/eio-charts ;
          gh repo sync https://github.com/luncher-org/eks-operator ;
          gh repo sync https://github.com/luncher-org/elemental ;
          gh repo sync https://github.com/luncher-org/elemental-channels ;
          gh repo sync https://github.com/luncher-org/elemental-docs ;
          gh repo sync https://github.com/luncher-org/elemental-obs ;
          gh repo sync https://github.com/luncher-org/elemental-operator ;
          gh repo sync https://github.com/luncher-org/elemental-product-docs ;
          gh repo sync https://github.com/luncher-org/elemental-toolkit ;
          gh repo sync https://github.com/luncher-org/elemental-ui ;
          gh repo sync https://github.com/luncher-org/ember-api-store ;
          gh repo sync https://github.com/luncher-org/etcd ;
          gh repo sync https://github.com/luncher-org/external-attacher ;
          gh repo sync https://github.com/luncher-org/external-provisioner ;
          gh repo sync https://github.com/luncher-org/external-resizer ;
          gh repo sync https://github.com/luncher-org/external-snapshotter ;
          gh repo sync https://github.com/luncher-org/flannel ;
          gh repo sync https://github.com/luncher-org/flannel-cni ;
          gh repo sync https://github.com/luncher-org/fleet ;
          gh repo sync https://github.com/luncher-org/fleet-dashboards ;
          gh repo sync https://github.com/luncher-org/fleet-docs ;
          gh repo sync https://github.com/luncher-org/fleet-e2e ;
          gh repo sync https://github.com/luncher-org/fleet-examples ;
          gh repo sync https://github.com/luncher-org/fleet-helm-charts ;
          gh repo sync https://github.com/luncher-org/fleet-product-docs ;
          gh repo sync https://github.com/luncher-org/fleet-test-data ;
          gh repo sync https://github.com/luncher-org/fluent-bit-package ;
          gh repo sync https://github.com/luncher-org/gcp-janitor ;
          gh repo sync https://github.com/luncher-org/gitjob ;
          gh repo sync https://github.com/luncher-org/gke-operator ;
          gh repo sync https://github.com/luncher-org/grpc-health-probe ;
          gh repo sync https://github.com/luncher-org/hamilton ;
          gh repo sync https://github.com/luncher-org/harvester-cloud ;
          gh repo sync https://github.com/luncher-org/harvester-csi-driver ;
          gh repo sync https://github.com/luncher-org/harvester-product-docs ;
          gh repo sync https://github.com/luncher-org/helm ;
          gh repo sync https://github.com/luncher-org/helm-locker ;
          gh repo sync https://github.com/luncher-org/helm-project-operator ;
          gh repo sync https://github.com/luncher-org/highlander ;
          gh repo sync https://github.com/luncher-org/hosted-providers-e2e ;
          gh repo sync https://github.com/luncher-org/hubble-ui ;
          gh repo sync https://github.com/luncher-org/hull ;
          gh repo sync https://github.com/luncher-org/hyperkube ;
          gh repo sync https://github.com/luncher-org/hyperkube-base ;
          gh repo sync https://github.com/luncher-org/icons ;
          gh repo sync https://github.com/luncher-org/image-build-addon-resizer ;
          gh repo sync https://github.com/luncher-org/image-build-base ;
          gh repo sync https://github.com/luncher-org/image-build-calico ;
          gh repo sync https://github.com/luncher-org/image-build-cluster-proportional-autoscaler ;
          gh repo sync https://github.com/luncher-org/image-build-cni-plugins ;
          gh repo sync https://github.com/luncher-org/image-build-containerd ;
          gh repo sync https://github.com/luncher-org/image-build-coredns ;
          gh repo sync https://github.com/luncher-org/image-build-crictl ;
          gh repo sync https://github.com/luncher-org/image-build-dns-nodecache ;
          gh repo sync https://github.com/luncher-org/image-build-etcd ;
          gh repo sync https://github.com/luncher-org/image-build-flannel ;
          gh repo sync https://github.com/luncher-org/image-build-ib-sriov-cni ;
          gh repo sync https://github.com/luncher-org/image-build-k8s-metrics-server ;
          gh repo sync https://github.com/luncher-org/image-build-kubernetes ;
          gh repo sync https://github.com/luncher-org/image-build-multus ;
          gh repo sync https://github.com/luncher-org/image-build-node-feature-discovery ;
          gh repo sync https://github.com/luncher-org/image-build-rke2-cloud-provider ;
          gh repo sync https://github.com/luncher-org/image-build-runc ;
          gh repo sync https://github.com/luncher-org/image-build-sriov-cni ;
          gh repo sync https://github.com/luncher-org/image-build-sriov-network-device-plugin ;
          gh repo sync https://github.com/luncher-org/image-build-sriov-network-resources-injector ;
          gh repo sync https://github.com/luncher-org/image-build-sriov-operator ;
          gh repo sync https://github.com/luncher-org/image-build-whereabouts ;
          gh repo sync https://github.com/luncher-org/image-mirror ;
          gh repo sync https://github.com/luncher-org/ingress-nginx ;
          gh repo sync https://github.com/luncher-org/install-docker ;
          gh repo sync https://github.com/luncher-org/istio-installer ;
          gh repo sync https://github.com/luncher-org/k3k ;
          gh repo sync https://github.com/luncher-org/k3s-product-docs ;
          gh repo sync https://github.com/luncher-org/k8s-intro-training ;
          gh repo sync https://github.com/luncher-org/klipper-helm ;
          gh repo sync https://github.com/luncher-org/klipper-lb ;
          gh repo sync https://github.com/luncher-org/kontainer-driver-metadata ;
          gh repo sync https://github.com/luncher-org/kube-api-auth ;
          gh repo sync https://github.com/luncher-org/kube-vip ;
          gh repo sync https://github.com/luncher-org/kubectl ;
          gh repo sync https://github.com/luncher-org/kuberlr-kubectl ;
          gh repo sync https://github.com/luncher-org/kubernetes ;
          gh repo sync https://github.com/luncher-org/kubernetes-provider-detector ;
          gh repo sync https://github.com/luncher-org/kubevirt-containerized-data-importer ;
          gh repo sync https://github.com/luncher-org/kubewarden-product-docs ;
          gh repo sync https://github.com/luncher-org/kubewarden-ui ;
          gh repo sync https://github.com/luncher-org/lasso ;
          gh repo sync https://github.com/luncher-org/livenessprobe ;
          gh repo sync https://github.com/luncher-org/local-path-provisioner ;
          gh repo sync https://github.com/luncher-org/loglevel ;
          gh repo sync https://github.com/luncher-org/longhorn-product-docs ;
          gh repo sync https://github.com/luncher-org/machine ;
          gh repo sync https://github.com/luncher-org/mapps-e2e ;
          gh repo sync https://github.com/luncher-org/metrics-server ;
          gh repo sync https://github.com/luncher-org/migration-agent ;
          gh repo sync https://github.com/luncher-org/mirrored-prometheus-operator-admission-webhook ;
          gh repo sync https://github.com/luncher-org/multus-cni ;
          gh repo sync https://github.com/luncher-org/neuvector-product-docs ;
          gh repo sync https://github.com/luncher-org/nfs-ganesha ;
          gh repo sync https://github.com/luncher-org/node-driver-registrar ;
          gh repo sync https://github.com/luncher-org/node-feature-discovery ;
          gh repo sync https://github.com/luncher-org/norman ;
          gh repo sync https://github.com/luncher-org/ob-team-charts ;
          gh repo sync https://github.com/luncher-org/observability-e2e ;
          gh repo sync https://github.com/luncher-org/opni ;
          gh repo sync https://github.com/luncher-org/opni-docs ;
          gh repo sync https://github.com/luncher-org/opni-drain-service ;
          gh repo sync https://github.com/luncher-org/opni-inference-service ;
          gh repo sync https://github.com/luncher-org/opni-ingest-plugin ;
          gh repo sync https://github.com/luncher-org/opni-preprocessing-service ;
          gh repo sync https://github.com/luncher-org/opni-training-controller ;
          gh repo sync https://github.com/luncher-org/opni-ui ;
          gh repo sync https://github.com/luncher-org/partner-charts ;
          gh repo sync https://github.com/luncher-org/partner-charts-ci ;
          gh repo sync https://github.com/luncher-org/partner-extensions ;
          gh repo sync https://github.com/luncher-org/permissions ;
          gh repo sync https://github.com/luncher-org/plugins ;
          gh repo sync https://github.com/luncher-org/private-registry-product-docs ;
          gh repo sync https://github.com/luncher-org/product-docs-playbook ;
          gh repo sync https://github.com/luncher-org/product-docs-supplemental-files ;
          gh repo sync https://github.com/luncher-org/product-docs-ui ;
          gh repo sync https://github.com/luncher-org/project-assets ;
          gh repo sync https://github.com/luncher-org/prometheus-auth ;
          gh repo sync https://github.com/luncher-org/prometheus-federator ;
          gh repo sync https://github.com/luncher-org/provisioning ;
          gh repo sync https://github.com/luncher-org/proxy ;
          gh repo sync https://github.com/luncher-org/qase-go ;
          gh repo sync https://github.com/luncher-org/quickstart ;
          gh repo sync https://github.com/luncher-org/rancher ;
          gh repo sync https://github.com/luncher-org/rancher-cleanup ;
          gh repo sync https://github.com/luncher-org/rancher-docs ;
          gh repo sync https://github.com/luncher-org/rancher-product-docs ;
          gh repo sync https://github.com/luncher-org/rancher-selinux ;
          gh repo sync https://github.com/luncher-org/rancher-turtles-e2e ;
          gh repo sync https://github.com/luncher-org/rancher.github.io ;
          gh repo sync https://github.com/luncher-org/rancher2-scaling ;
          gh repo sync https://github.com/luncher-org/rancherd ;
          gh repo sync https://github.com/luncher-org/remotedialer ;
          gh repo sync https://github.com/luncher-org/renovate-config ;
          gh repo sync https://github.com/luncher-org/rke ;
          gh repo sync https://github.com/luncher-org/rke-tools ;
          gh repo sync https://github.com/luncher-org/rke1-docs ;
          gh repo sync https://github.com/luncher-org/rke2 ;
          gh repo sync https://github.com/luncher-org/rke2-charts ;
          gh repo sync https://github.com/luncher-org/rke2-docs ;
          gh repo sync https://github.com/luncher-org/rke2-packaging ;
          gh repo sync https://github.com/luncher-org/rke2-product-docs ;
          gh repo sync https://github.com/luncher-org/rke2-selinux ;
          gh repo sync https://github.com/luncher-org/rke2-upgrade ;
          gh repo sync https://github.com/luncher-org/samba-backupstore ;
          gh repo sync https://github.com/luncher-org/saml ;
          gh repo sync https://github.com/luncher-org/scans ;
          gh repo sync https://github.com/luncher-org/security-scan ;
          gh repo sync https://github.com/luncher-org/shell ;
          gh repo sync https://github.com/luncher-org/shepherd ;
          gh repo sync https://github.com/luncher-org/spdk ;
          gh repo sync https://github.com/luncher-org/stackstate-product-docs ;
          gh repo sync https://github.com/luncher-org/steve ;
          gh repo sync https://github.com/luncher-org/storybook ;
          gh repo sync https://github.com/luncher-org/support-bundle-kit ;
          gh repo sync https://github.com/luncher-org/supportability-review-app ;
          gh repo sync https://github.com/luncher-org/system-agent ;
          gh repo sync https://github.com/luncher-org/system-agent-installer-k3s ;
          gh repo sync https://github.com/luncher-org/system-agent-installer-rke2 ;
          gh repo sync https://github.com/luncher-org/system-charts ;
          gh repo sync https://github.com/luncher-org/system-upgrade-controller ;
          gh repo sync https://github.com/luncher-org/systemd-node ;
          gh repo sync https://github.com/luncher-org/terraform-aws-access ;
          gh repo sync https://github.com/luncher-org/terraform-aws-rke2 ;
          gh repo sync https://github.com/luncher-org/terraform-aws-rke2-clusters ;
          gh repo sync https://github.com/luncher-org/terraform-aws-rke2-live-example ;
          gh repo sync https://github.com/luncher-org/terraform-aws-server ;
          gh repo sync https://github.com/luncher-org/terraform-github-rke2-download ;
          gh repo sync https://github.com/luncher-org/terraform-local-rke2-config ;
          gh repo sync https://github.com/luncher-org/terraform-local-rke2-hardening ;
          gh repo sync https://github.com/luncher-org/terraform-null-rke2-install ;
          gh repo sync https://github.com/luncher-org/terraform-provider-rancher2 ;
          gh repo sync https://github.com/luncher-org/terraform-provider-rke ;
          gh repo sync https://github.com/luncher-org/terraform-rancher2-aws ;
          gh repo sync https://github.com/luncher-org/tests ;
          gh repo sync https://github.com/luncher-org/tf-rancher-up ;
          gh repo sync https://github.com/luncher-org/tfp-automation ;
          gh repo sync https://github.com/luncher-org/traefik ;
          gh repo sync https://github.com/luncher-org/turtles ;
          gh repo sync https://github.com/luncher-org/turtles-docs ;
          gh repo sync https://github.com/luncher-org/turtles-product-docs ;
          gh repo sync https://github.com/luncher-org/ui ;
          gh repo sync https://github.com/luncher-org/ui-locales ;
          gh repo sync https://github.com/luncher-org/ui-plugin-charts ;
          gh repo sync https://github.com/luncher-org/ui-plugin-examples ;
          gh repo sync https://github.com/luncher-org/ui-plugin-operator ;
          gh repo sync https://github.com/luncher-org/ui-plugin-server ;
          gh repo sync https://github.com/luncher-org/ux ;
          gh repo sync https://github.com/luncher-org/vagrant-rke2 ;
          gh repo sync https://github.com/luncher-org/vexhub ;
          gh repo sync https://github.com/luncher-org/virtual-clusters-ui ;
          gh repo sync https://github.com/luncher-org/vsphere-charts ;
          gh repo sync https://github.com/luncher-org/webhook ;
          gh repo sync https://github.com/luncher-org/wharfie ;
          gh repo sync https://github.com/luncher-org/whereabouts ;
          gh repo sync https://github.com/luncher-org/windows ;
          gh repo sync https://github.com/luncher-org/windows_exporter-package ;
          gh repo sync https://github.com/luncher-org/wins ;
          gh repo sync https://github.com/luncher-org/wrangler ;
          gh repo sync https://github.com/luncher-org/wrangler-cli ;
          gh repo sync https://github.com/luncher-org/yip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
